# Generated by Django 5.1.6 on 2025-03-03 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_sio3packmodelsolution_package_and_more"),
        ("sinolpack", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sinolpackadditionalfile",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="additional_files", to="common.sio3package"
            ),
        ),
        migrations.AlterField(
            model_name="sinolpackattachment",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="common.sio3package"
            ),
        ),
        migrations.AlterField(
            model_name="sinolpackconfig",
            name="package",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="config", to="common.sio3package"
            ),
        ),
    ]
