# Generated by Django 5.1.6 on 2025-03-03 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sio3packmodelsolution",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="model_solutions", to="common.sio3package"
            ),
        ),
        migrations.AlterField(
            model_name="sio3packnametranslation",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="name_translations", to="common.sio3package"
            ),
        ),
        migrations.AlterField(
            model_name="sio3packstatement",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="statements", to="common.sio3package"
            ),
        ),
    ]
