# Generated by Django 4.2.20 on 2025-05-05 09:29

from django.db import migrations, models
import django.db.models.deletion
import sio3pack.django.common.models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_sio3packnametranslation_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SIO3PackTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("test_id", models.CharField(max_length=255, verbose_name="id")),
                ("group", models.CharField(max_length=255, verbose_name="group")),
                (
                    "input_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sio3pack.django.common.models.make_problem_filename,
                        verbose_name="input file",
                    ),
                ),
                (
                    "output_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sio3pack.django.common.models.make_problem_filename,
                        verbose_name="output file",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tests", to="common.sio3package"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SIO3PackMainModelSolution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_file",
                    models.FileField(
                        upload_to=sio3pack.django.common.models.make_problem_filename, verbose_name="source file"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_model_solution",
                        to="common.sio3package",
                    ),
                ),
            ],
        ),
    ]
