# Generated by Django 4.2.20 on 2025-05-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_sio3packtest_sio3packmainmodelsolution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sio3packtest",
            options={"verbose_name": "test", "verbose_name_plural": "tests"},
        ),
        migrations.AlterUniqueTogether(
            name="sio3packtest",
            unique_together={("package", "name", "test_id", "group")},
        ),
        migrations.CreateModel(
            name="SIO3PackWorkflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("workflow_raw", models.TextField(verbose_name="workflow")),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="workflows", to="common.sio3package"
                    ),
                ),
            ],
            options={
                "verbose_name": "workflow",
                "verbose_name_plural": "workflows",
            },
        ),
    ]
