name: pytest-arch
run-name: Run pytest on Arch Linux
on:
  push:
    branches: 'main'
  pull_request:
jobs:
  pytest:
    runs-on: archlinux-latest
    strategy:
        matrix:
            python-version: ["3.10", "3.13"]
    name: pytest-arch-python-${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip3 install .[tests]
      - name: Run pytest without Django
        env:
          PYTEST_ADDOPTS: "--color=yes"
        run: |
          python3 -m pytest -v -n auto
      - name: Run pytest with Django
        env:
          PYTEST_ADDOPTS: "--color=yes"
        run: |
          python3 -m install .[tests,django_tests,django]
          ./tests/test_django/manage.py migrate
          python3 -m pytest -v -n auto
